//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransAPi.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUp
    {
        public int LookupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> RefId { get; set; }
        public string ItemName { get; set; }
        public string ItemId { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
